name: Run Automated script when PR Trigger
on:
  pull_request:
    types:
      - opened

jobs:
  wdio:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10
        
      - name: Install Node Modules
        run: npm install 
        
      - name: Permission to .sh files
        run: chmod 777 e2e-tests.sh
             chmod 777 all-tests.sh 

      - name: Run WDIO tests
        run: npm run test:e2e
  
  upload-artifacts:
    needs: wdio
    runs-on: macos-latest

    steps:
      - name: Download artifacts on failure
        if: ${{ always() }}
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts
          path: path/to/download
